version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  redis:
    image: redis
    ports:
      - "6379:6379"
  fedora:
    image: osul/fcrepo:4.6.0
    ports:
      - "8984:8080"
  solr:
      image: solr:5.5
      ports:
        - "8983:8983"
      volumes:
        - ./solr/config:/opt/config
  app:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/hydra-docker-demo
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - fedora
      - solr
